"""
Do not edit this file
"""
from config import client

search_fn = client.search()

channel_fn = client.channels()

playlists_fn = client.playlists()

playlist_items_fn = client.playlistItems()

video_fn = client.videos()